### Create Movie
POST http://localhost:5032/api/v1/movies/a4422927-4a74-4be7-b227-6702db424232
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmFtZWlkIjoiYjhhMzRhZWYtOGM0Zi00NzM1LTgwMTQtOTcwYzA5MTMwMGU2IiwibmJmIjoxNzUyNTQwNzM2LCJleHAiOjE3NTI1NDQzMzYsImlhdCI6MTc1MjU0MDczNiwiaXNzIjoiTW92aWVzSXNzdWVyIiwiYXVkIjoiTW92aWVzQXVkaWVuY2UifQ.Whv_TknZChDK0D0Mpluky_NdUws-M1RL4xKiC9gXFBw

{
  "title": "Sweeney Todd",
  "yearOfRelease": 2007,
  "genres": ["Shooter", "Sci-Fi", "Action"]
}

### Get All Movies
GET http://localhost:5032/api/v1/movies?sortBy=-year
Content-Type: application/json

### Get All Movies With User Ratings
GET http://localhost:5032/api/v1/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJyb2xlIjoiVXNlciIsIm5hbWVpZCI6IjQyYmFlOTcwLTNmMjgtNDk0Ni04MDg2LWIzOGNhZDc3YzQ0NCIsIm5iZiI6MTc1MjUxMTI0NSwiZXhwIjoxNzUyNTE0ODQ1LCJpYXQiOjE3NTI1MTEyNDUsImlzcyI6Ik1vdmllc0lzc3VlciIsImF1ZCI6Ik1vdmllc0F1ZGllbmNlIn0.5e2Y-UK-FxlKdYtqE4kdkVI-R19Ui4p3Vo58bCj9eS8

### Get Movie by ID
GET http://localhost:5032/api/v1/movies/b7422927-4a74-4be7-b227-6702db424230
Content-Type: application/json

### Get Movies by Slug
GET http://localhost:5032/api/v1/movies/inception-2-2018

### Update Movie
PUT http://localhost:5032/api/v1/movies/b7422927-4a74-4be7-b227-6702db424230
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmFtZWlkIjoiYjhhMzRhZWYtOGM0Zi00NzM1LTgwMTQtOTcwYzA5MTMwMGU2IiwibmJmIjoxNzUyMzYxMDY4LCJleHAiOjE3NTIzNjQ2NjgsImlhdCI6MTc1MjM2MTA2OCwiaXNzIjoiTW92aWVzSXNzdWVyIiwiYXVkIjoiTW92aWVzQXVkaWVuY2UifQ.hC42to_luPYMHpuTliPB52Y3lf-6rsyA_wu_uTfSPRM

{
  "title": "Inception 2 Updated",
  "yearOfRelease": 2014,
  "genre": ["Action", "Sci-Fi", "Thriller"]
}

### Delete Movie
DELETE http://localhost:5032/api/v1/movies/b7422927-4a74-4be7-b227-6702db424230
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzUyMDk3NTgxLCJleHAiOjE3NTIxMDExODEsImlhdCI6MTc1MjA5NzU4MSwiaXNzIjoiTW92aWVzSXNzdWVyIiwiYXVkIjoiTW92aWVzQXVkaWVuY2UifQ.xYmaTBAZsprhPX-77qJXKfzBv61OzVwx8XKCy9JEyG0


### Rate Movie
POST http://localhost:5032/api/v1/movies/b7422927-4a74-4be7-b227-6702db424230/ratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJyb2xlIjoiVXNlciIsIm5hbWVpZCI6IjQyYmFlOTcwLTNmMjgtNDk0Ni04MDg2LWIzOGNhZDc3YzQ0NCIsIm5iZiI6MTc1MjUxNTMyMSwiZXhwIjoxNzUyNTE4OTIxLCJpYXQiOjE3NTI1MTUzMjEsImlzcyI6Ik1vdmllc0lzc3VlciIsImF1ZCI6Ik1vdmllc0F1ZGllbmNlIn0.MR0_e0pfF0chLaMWs1IIwRcVZClADiTbt3X-wVPfEzI

{
  "rating": 5
}

### Delete Movie Ratings
DELETE http://localhost:5032/api/v1/movies/b7422927-4a74-4be7-b227-6702db424230/ratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJyb2xlIjoiVXNlciIsIm5hbWVpZCI6IjQyYmFlOTcwLTNmMjgtNDk0Ni04MDg2LWIzOGNhZDc3YzQ0NCIsIm5iZiI6MTc1MjUxMTI0NSwiZXhwIjoxNzUyNTE0ODQ1LCJpYXQiOjE3NTI1MTEyNDUsImlzcyI6Ik1vdmllc0lzc3VlciIsImF1ZCI6Ik1vdmllc0F1ZGllbmNlIn0.5e2Y-UK-FxlKdYtqE4kdkVI-R19Ui4p3Vo58bCj9eS8

### Get Movie Ratings
GET http://localhost:5032/api/v1/ratings/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJyb2xlIjoiVXNlciIsIm5hbWVpZCI6IjQyYmFlOTcwLTNmMjgtNDk0Ni04MDg2LWIzOGNhZDc3YzQ0NCIsIm5iZiI6MTc1MjUxNTMyMSwiZXhwIjoxNzUyNTE4OTIxLCJpYXQiOjE3NTI1MTUzMjEsImlzcyI6Ik1vdmllc0lzc3VlciIsImF1ZCI6Ik1vdmllc0F1ZGllbmNlIn0.MR0_e0pfF0chLaMWs1IIwRcVZClADiTbt3X-wVPfEzI