### Test JWT Token Generation
POST http://localhost:5131/token
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Test JWT Token Validation
POST http://localhost:5131/token
Content-Type: application/json

{
    "username": "user",
    "password": "user"
}